---
- hosts: localhost
  remote_user: test
  become: yes
  become_method: sudo

  tasks:
   - name: checking the state of nginx
     service: 
      name: apache2
      state: started
  
  tasks:
   - name: index.html updating task
     template:
       src=/srv/index.html
       dest=/var/www/html/index.html
